# Generated by Django 2.1.2 on 2019-01-29 07:26

import django.db.models.deletion
import model_utils.fields
from django.db import connection
from django.db import migrations, models

if connection.vendor == 'postgresql':
    from django.contrib.postgres.fields import JSONField
else:
    from jsonfield import JSONField


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('task', models.CharField(choices=[('base_test', 'base_test')], max_length=100)),
                ('status', model_utils.fields.StatusField(
                    choices=[('created', 'created'), ('start', 'start'), ('active', 'active'), ('done', 'done'),
                             ('del', 'del')], default='created', max_length=100, no_check_for_status=True)),
                ('task_result', JSONField(blank=True, default=dict)),
                ('closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
