# Generated by Django 2.1.5 on 2019-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltask',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
