# Generated by Django 2.1.5 on 2019-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0003_auto_20190215_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='celery_task',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
