# Generated by Django 3.1.4 on 2020-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0004_modeltask_celery_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltask',
            name='task_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
