# Generated by Django 3.2 on 2021-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0005_auto_20201216_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
